### ISSUE TITLE
ileNotFoundError: [Errno 2] No such file or directory; BTW NO COMMENTS!!

### ISSUE THREAD

**Issue by Arlan2191** [0x5eba/Skin-Cancer-Segmentation#2]
Traceback (most recent call last):
  File "create_dataset.py", line 28, in <module>
    data = json.load(open(DIR_DATA + f"Descriptions/ISIC_{num}"))
FileNotFoundError: [Errno 2] No such file or directory: 'f:\\Anaconda\\Skin-Cancer-Segmentation/Data/Descriptions/ISIC_0000240'

I set the values of i in line 25 in the create_dataset.py file from 1367-13786 into 240-14559. 
And I have manually downloaded that dataset from the ISIC Archive;for the download_dataset.py seems to only download the descriptions and not the images and I left on all night. 
My manually downloaded dataset was placed at the data folder of this file. The descriptions subfolder contain the .json files and the images subfolder contatin the .jpg files.

My directories: 
F:\Anaconda\Skin-Cancer-Segmentation\Data
F:\Anaconda\Skin-Cancer-Segmentation\Data\Images
F:\Anaconda\Skin-Cancer-Segmentation\Data\Descriptions

The code:
import cv2
import numpy as np
import json
import os
import matplotlib.pyplot as plt

from Mask.config import Config
import Mask.utils as utils
import Mask.model as modellib
import Mask.visualize as visualize
from Mask.model import log

from Mask.magicwand import SelectionWindow

dir_path = os.path.dirname(os.path.realpath(__file__))
DIR_NUMPYDATA = dir_path + "/NumpyData/"
DIR_DATA = dir_path + "/Data/"

def get_mask(img, i):
    selection = SelectionWindow('Selection Window', img, i, DIR_NUMPYDATA, 8)
    selection.show()

for i in range(240, 14559):

    num = str(i).zfill(7)
    data = json.load(open(DIR_DATA + f"Descriptions\ISIC_{num}"))

    if data["meta"]["clinical"]["benign_malignant"] is None:
        continue

    if data["meta"]["clinical"]["benign_malignant"] != "malignant" and data["meta"]["clinical"]["benign_malignant"] != "benign":
        continue

    img = cv2.imread(DIR_DATA + f"Images\ISIC_{num}.jpg")
    img = cv2.resize(img, (128, 128))

    get_mask(img, num)

    with open(DIR_NUMPYDATA + f"ISIC_{num}_IMG.npy", "w") as f:
        np.save(DIR_NUMPYDATA + f"ISIC_{num}_IMG", img)

PLEASE HELP!

**Comment by 0x5eba** [comment]
Hi Arlan2191,
Sorry for all that problems, right now I am working on another project that takes me the whole day.

Now I have fixed everything.
But unfortunately you have to download the dataset again, if you used my previous script.

Let me know if you have some problem.
Good Day!

**Comment by Arlan2191** [comment]
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    mask, class_ids = dataset_train.load_mask(image_id)
  File "main.py", line 83, in load_mask
    mask = info["mask"].astype(np.uint8)
AttributeError: 'NoneType' object has no attribute 'astype'

Line 127
    mask, class_ids = dataset_train.load_mask(image_id)

Line 83
        mask = info["mask"].astype(np.uint8)

Is this a module I have to install? Do help trying to solve for about 2 hours now.. bit of a beginner :)

**Comment by 0x5eba** [comment]
I think it's because some masks doesn't exist in the folder.

Update your main.py and test.py with the new one and try again `python3 main.py` it should works.

**Comment by Arlan2191** [comment]
I did download the whole dataset but it seems that there is no segmentation folder

**Comment by 0x5eba** [comment]
Try with `python3 download_archive.py -s --no-images`

**Comment by Arlan2191** [comment]
Thanks for all the replies! Question though, is it possible like to do training by batch?

**Comment by 0x5eba** [comment]
The Mask-RCNN architecture already do that, the problem is feed the data without run out of memory

**Comment by Arlan2191** [comment]
It seems during running main.py it only uses up my memory (15.5 out 15.9) and the gpu of only 1% (NVIDIA GTX 1060) ... Because of such main.py ends up in failed allocation of [insert huge number here] bytes. Need help! So does it mean I need to change this part of the program?

`
class MolesConfig(Config):
    ''' 
    MolesConfig:
        Contain the configuration for the dataset + those in Config
    '''
    NAME = "moles"
    GPU_COUNT = 1 # put 2 or more if you are 1 or more gpu
    IMAGES_PER_GPU = 5 # if you are a gpu you are choose how many image to process per gpu
    NUM_CLASSES = 1 + 2  # background + (malignant , benign)
    IMAGE_MIN_DIM = 128
    IMAGE_MAX_DIM = 128

    # hyperparameter
    LEARNING_RATE = 0.001
    STEPS_PER_EPOCH = 100
    VALIDATION_STEPS = 5
`

**Comment by Arlan2191** [comment]
It produces an error as shown below:

Traceback (most recent call last):
  File "main.py", line 99, in <module>
    img = cv2.imread(path_data+"Images/"+filename+".jpg")
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:55: error: (-4:Insufficient memory) Failed to allocate 18289152 bytes in function 'cv::OutOfMemoryError'

**Comment by Arlan2191** [comment]
I understood now the problem on the memory allocation. Thanks for the help! But still I need further assistance! 

error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

It appeared during epoch 1/30
And points at this line :

                  mask = cv2.resize(mask, (128, 128))

Due to this, the training wouldn't proceed! Thanks in advance for your reply!

**Comment by 0x5eba** [comment]
Try to change this part:
```
for filename in os.listdir(path_data+"Descriptions/"):
    data = json.load(open(path_data+"/Descriptions/"+filename))
    img = cv2.imread(path_data+"Images/"+filename+".jpg")
    img = cv2.resize(img, (128, 128))
    mask = cv2.imread(path_data+"Segmentation/"+filename+"_expert.png")
    mask = cv2.resize(mask, (128, 128))

    if not mask or not img:
        continue
```

With:
```
for filename in os.listdir(path_data+"Descriptions/"):
    data = json.load(open(path_data+"/Descriptions/"+filename))
    img = cv2.imread(path_data+"Images/"+filename+".jpg")
    if not img:
        continue
    img = cv2.resize(img, (128, 128))
    mask = cv2.imread(path_data+"Segmentation/"+filename+"_expert.png")
    if not mask:
        continue
    mask = cv2.resize(mask, (128, 128))
```

And for the memory allocation change `for filename in os.listdir(path_data+"Descriptions/"):` with `for filename in os.listdir(path_data+"Descriptions/")[1000:]:`

**Comment by Arlan2191** [comment]
Thank you for the reply, but it seems another error occurred. It is a 
Line <no. here> on the "mtrand.pyx" in mtrand.RandomState.choice
Value Error: a must be non-empty

**Comment by Arlan2191** [comment]
And uhm also for comparison purposes in the future when it works, can I ask for a copy of trained model please. You have been really helpful and thank you for that!

**Comment by Arlan2191** [comment]
Also, what version of python are you using?
